### PR TITLE
use rapier3d for collision detection

### PR DESCRIPTION
**Pull request by AnotherCoolDude**
Hey, 
maybe it's good to invest into a physics library from the early beginning? I think the code to make it work is rather easy and won't make the tutorial too complex. But that's up to you, of course. Keep those tutorials coming 👍

### CODE REVIEW

**Comment by mwbryant** [comment]
I really appreciate you putting this together! The problem I have with including it into the main line tutorial is I would feel obligated to explain every line and that would quickly turn into a rapier tutorial (which I still really need to do but other things keep coming up).  For example I would need to cover rigid bodies, colliders, collision types, ect. 

I agree it's not a lot but there are more fundamental bevy things like input and events I'd like to spend the early time on in the tutorials.  But there's also probably value in showing usage of some more external bevy plugins early on because that's a big part of practically using Bevy so I'm torn.

I don't think there's anymore physics than what I already have in the my vision for the project.  All we really needed was collision detection between bullets and enemies, no dynamics or anything.

I'm currently leaning toward having this PR be a branch and then mentioning it in the opening of the next tutorial as a place people who are interested can go look.  But I'm open to suggestions and I'd love your input on this approach.

**Comment by AnotherCoolDude** [comment]
If you feel like it is too early or simply too much to take in, then you should not merge. You are probably right: It's not a lot of code, but it requires a basic understanding of how the library works. That would take time to explain. Dismissing the PR or keeping it in a separate branch is both fine for me 👍

**Comment by mwbryant** [comment]
I like the approach of separate branch and pointing to it in the next video so that's what I'm going to do.  Rapier definitely deserves a deep dive soon because it's a bit overwhelming but incredibly powerful.

**Comment by mwbryant** [comment]
Physics branch created

**Pull request closed without merging**
